channels:
- conda-forge
dependencies:
- python=3.10.3
- pip
- pip:
  - mlflow
  - cloudpickle==2.0.0
  - psutil==5.9.0
  - scikit-learn==1.0.2
  - src==1.0.0
  - typing-extensions==4.1.1
  - xgboost==1.5.2
name: mlflow-env
